[package]
name = "pyflyer"
version = "0.2.0"
authors = ["Alexander Quessy"]
edition = "2021"
description = "A PyO3 library providing methods to access the 12DoF non-linear aircaft simulation found in flyer-rs within a Python program. This library was aimed to link flyer-rs to FlyerEnv."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyflyer"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bevy_server"
path = "src/bin/bevy_server.rs"

[dependencies]
flyer = { path = "flyer-rs" }
glam = { version = "0.24.2", features = ["mint", "serde"] }
pyo3 = { version = "0.23.1", features = ["extension-module"] }
aerso = { git = "https://github.com/rob-clarke/aerso.git" }
tiny-skia = "0.11.1"
nalgebra = "0.29.0"
argmin = "0.8.1"
bevy = { version = "0.15" }
numpy = "0.23.0"
rand = "0.8.5"
rand_chacha = { version = "0.3.1", features = ["serde"] }
ndarray = "0.16.1"
crossbeam-channel = "0.5.14"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9"
# Serialization
